version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: db-fastservice-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fastservice
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - fastservice-network
  
  api-fastservice:
    image: juniorsilvacc/api-fastservice
    container_name: api-fastservice
    restart: always
    build: .
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/fastservice
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - postgres
    networks:
      - fastservice-network
      
networks:
  fastservice-network:
    driver: bridge