version: '3.9'

services:
  postgres:
    image: 'postgres:alpine'
    container_name: db-fastservice-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'fastservice'