CREATE TABLE tb_user (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email  VARCHAR(100) NOT NULL,
	cpf  VARCHAR(11) NOT NULL,
	avatar  VARCHAR(255),
	password  VARCHAR(255) NOT NULL,
	profile INTEGER NOT NULL,
	createdAt DATE
);