CREATE TABLE tb_user (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email  VARCHAR(100) NOT NULL UNIQUE,
	cpf  VARCHAR(11) NOT NULL UNIQUE,
	avatar  VARCHAR(255),
	password  VARCHAR(255) NOT NULL,
	account_non_expired BOOLEAN DEFAULT TRUE NULL,
	account_non_locked BOOLEAN DEFAULT TRUE NULL,
	credentials_non_expired BOOLEAN DEFAULT TRUE NULL,
	enabled BOOLEAN DEFAULT TRUE NULL
);